### ISSUE TITLE
FornaxA.fits file not in fits format

### ISSUE THREAD

**Issue by basuparth** [fermi-lat/extendedArchive#7]
I have FornaxA in my roi and while running a standard analysis I run into the error which says  

Caught N3tip12TipExceptionE at the top level: File not in FITS or Root format: /home/parth/SINP/enrico/Data/catalog/Extended_archive_v15/Templates/FornaxA.fits
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/home/parth/SINP/Source/FST_Analyser.py in <module>()
     49 my_apps.diffResps['srcmdl'] = 'source_model.xml'
     50 my_apps.diffResps['irfs'] = 'P8R3_SOURCE_V2'
---> 51 my_apps.diffResps.run()
     52 
     53 import pyLikelihood

/home/parth/anaconda2/envs/fermi1/lib/python2.7/site-packages/fermitools/GtApp.pyc in run(self, print_command, catchError, dry_run, **kwds)
     74                     input.close()
     75                     output.close()
---> 76                     raise RuntimeError, self.appName + " execution failed"
     77             input.close()
     78             output.close()

RuntimeError: gtdiffrsp execution failed

**Comment by nmirabal** [comment]
Are you using the latest Fermitools version?
https://github.com/fermi-lat/Fermitools-conda/wiki/Installation-Instructions

**Comment by basuparth** [comment]
Fermitools version is 1.0.1. , I updated to 1.0.2 today but the error still persists.

**Comment by nmirabal** [comment]
Are you using the latest version of the make4FGLxml.py to create the XML file?. You can follow the FSSC python tutorial is at the following link
https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/python_tutorial.html

**Comment by basuparth** [comment]
yes I used the make4FGLxml.py while following the FSSC tutorial. I just stored my FornaxA.fits file in the enrico directory. 
[FST_Analyser.txt](https://github.com/fermi-lat/extendedArchive/files/3107789/FST_Analyser.txt)

**Comment by nmirabal** [comment]
I believe the problem is with the path. I am not sure if it's a permissions issue. By default the make4FGLxml.py file puts the following path  $(FERMI_DIR)/data/pyBurstAnalysisGUI/templates/. Can you try without specifying extDir?

**Comment by nmirabal** [comment]
Also as part of the 4FGL release, there is a new version of the extended files.To upgrade you need to launch gtburst and in the upper menu click on Update and Update to the latest version

**Comment by basuparth** [comment]
Thanks. After removing the extDir path and updating gtburst everything works fine.
